on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: BitComet
          token: ${{ secrets.PAT }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Peek
        run: python check-update.py

      - name: Bump
        run: |
          git config --global user.name 'Headless'
          git config --global user.email 'headless@example.com'
          git commit -am "Bump version" || true
          git push